name: .NET

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: windows-latest

    steps:
    # Устанавливаем .NET SDK
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    # Восстановление зависимостей
    - name: Restore dependencies
      run: dotnet restore TelegramAntispamBot.sln

    # Сборка приложения
    - name: Build solution
      run: dotnet build TelegramAntispamBot.sln --configuration Release --no-restore

    # Запуск тестов
    - name: Run unit tests
      run: dotnet test TelegramAntispamBot.Tests/TelegramAntispamBot.Tests.csproj --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"
          
    # Запуск билда на Render после успешных тестов
    - name: Trigger Render build
      if: success() 
      env:
        RENDER_ANTISPAM_BOT_KEY: ${{ secrets.RENDER_ANTISPAM_BOT_KEY }} # Секретный ключ API Render
      shell: pwsh
      run: |
        $headers = @{
            "Authorization" = "Bearer $env:RENDER_ANTISPAM_BOT_KEY"
            "Content-Type" = "application/json"
        }
        $body = "{}" | ConvertTo-Json
        Invoke-RestMethod -Uri "https://api.render.com/v1/services/srv-ctaoq5hu0jms73f1l3q0/deploys" -Method Post -Headers $headers -Body $body   
